import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { HeroUiProvider, NextThemeProvider, TanstackQueryProvider } from "@/contexts";

import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BetLive24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} ${geistMono.variable} antialiased`}>
        <HeroUiProvider>
          <NextThemeProvider>
            <TanstackQueryProvider>{children}</TanstackQueryProvider>
          </NextThemeProvider>
        </HeroUiProvider>
      </body>
    </html>
  );
}
